# Generated by Django 3.2.9 on 2022-01-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('news', '0009_auto_20211230_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, default='AnonymousAuthor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='authors.author'),
        ),
    ]
