# Generated by Django 3.2.9 on 2022-01-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20220113_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
    ]
