# Generated by Django 3.2.9 on 2022-01-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_tag_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='h1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_robots',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
